#ifndef HTML_DATA_H
#define HTML_DATA_H

const char *html_data =
"<!DOCTYPE html>"
"<html lang='pt-BR'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Estação Meteorológica</title>"
"<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box;font-family:'Segoe UI',sans-serif;}"
"body{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;min-height:100vh;padding:20px;}"
".container{max-width:1200px;margin:0 auto;background:rgba(255,255,255,0.1);border-radius:15px;padding:20px;backdrop-filter:blur(10px);}"
"header{text-align:center;margin-bottom:30px;}"
"h1{font-size:2.5rem;margin-bottom:10px;color:#64ffda;text-shadow:2px 2px 4px rgba(0,0,0,0.3);}"
".subtitle{color:#a0aec0;font-size:1.1rem;}"
".dashboard{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px;margin-bottom:20px;}"
".card{background:rgba(30,41,59,0.8);border-radius:12px;padding:20px;text-align:center;border:1px solid rgba(255,255,255,0.2);transition:transform 0.3s ease;}"
".card:hover{transform:translateY(-5px);}"
".card-icon{font-size:3rem;margin-bottom:15px;display:block;}"
".temperature .card-icon{color:#ff6b6b;}"
".humidity .card-icon{color:#4ecdc4;}"
".pressure .card-icon{color:#45b7d1;}"
".altitude .card-icon{color:#96ceb4;}"
".card-title{font-size:1.2rem;margin-bottom:10px;color:#e2e8f0;}"
".card-value{font-size:2.5rem;font-weight:bold;margin-bottom:5px;}"
".temperature .card-value{color:#ff6b6b;}"
".humidity .card-value{color:#4ecdc4;}"
".pressure .card-value{color:#45b7d1;}"
".altitude .card-value{color:#96ceb4;}"
".card-unit{font-size:1rem;color:#a0aec0;}"
".status-indicator{display:inline-block;width:12px;height:12px;border-radius:50%;background:#4ade80;margin-left:10px;animation:pulse 2s infinite;}"
"@keyframes pulse{0%{opacity:1;}50%{opacity:0.5;}100%{opacity:1;}}"
".last-update{text-align:center;color:#a0aec0;font-size:0.9rem;margin-top:20px;padding-top:15px;border-top:1px solid rgba(255,255,255,0.2);}"
".weather-summary{background:rgba(30,41,59,0.8);border-radius:12px;padding:20px;margin-top:20px;text-align:center;}"
".weather-icon{font-size:4rem;margin-bottom:15px;color:#ffd93d;}"
".weather-description{font-size:1.3rem;color:#e2e8f0;}"
"@media(max-width:768px){.dashboard{grid-template-columns:1fr;}h1{font-size:2rem;}.card-value{font-size:2rem;}}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<header>"
"<h1><i class='fas fa-cloud-sun'></i> Estação Meteorológica</h1>"
"<p class='subtitle'>Monitoramento em Tempo Real <span class='status-indicator'></span></p>"
"</header>"
"<div class='dashboard'>"
"<div class='card temperature'>"
"<i class='fas fa-thermometer-half card-icon'></i>"
"<div class='card-title'>Temperatura</div>"
"<div class='card-value' id='temperature'>25.4</div>"
"<div class='card-unit'>°C</div>"
"</div>"
"<div class='card humidity'>"
"<i class='fas fa-tint card-icon'></i>"
"<div class='card-title'>Umidade</div>"
"<div class='card-value' id='humidity'>68</div>"
"<div class='card-unit'>%</div>"
"</div>"
"<div class='card pressure'>"
"<i class='fas fa-gauge-high card-icon'></i>"
"<div class='card-title'>Pressão</div>"
"<div class='card-value' id='pressure'>1013.2</div>"
"<div class='card-unit'>hPa</div>"
"</div>"
"<div class='card altitude'>"
"<i class='fas fa-mountain card-icon'></i>"
"<div class='card-title'>Altitude</div>"
"<div class='card-value' id='altitude'>542</div>"
"<div class='card-unit'>m</div>"
"</div>"
"</div>"
"<div class='weather-summary'>"
"<i class='fas fa-sun weather-icon' id='weatherIcon'></i>"
"<div class='weather-description' id='weatherDescription'>Condições Ideais</div>"
"</div>"
"<div class='last-update'>"
"<i class='fas fa-clock'></i> Última atualização: <span id='timestamp'></span>"
"</div>"
"</div>"
"<script>"
"const weatherData={temperature:25.4,humidity:68,pressure:1013.2,altitude:542};"
"function updateWeatherData(){"
"weatherData.temperature=(20+Math.random()*15).toFixed(1);"
"weatherData.humidity=Math.floor(40+Math.random()*40);"
"weatherData.pressure=(1000+Math.random()*30).toFixed(1);"
"weatherData.altitude=Math.floor(500+Math.random()*100);"
"document.getElementById('temperature').textContent=weatherData.temperature;"
"document.getElementById('humidity').textContent=weatherData.humidity;"
"document.getElementById('pressure').textContent=weatherData.pressure;"
"document.getElementById('altitude').textContent=weatherData.altitude;"
"updateWeatherSummary();"
"updateTimestamp();"
"}"
"function updateWeatherSummary(){"
"const temp=parseFloat(weatherData.temperature);"
"const humidity=parseInt(weatherData.humidity);"
"const iconElement=document.getElementById('weatherIcon');"
"const descElement=document.getElementById('weatherDescription');"
"if(temp>30){"
"iconElement.className='fas fa-sun weather-icon';"
"iconElement.style.color='#ff6b6b';"
"descElement.textContent='Tempo Quente';"
"}else if(temp<15){"
"iconElement.className='fas fa-snowflake weather-icon';"
"iconElement.style.color='#64ffda';"
"descElement.textContent='Tempo Frio';"
"}else if(humidity>80){"
"iconElement.className='fas fa-cloud-rain weather-icon';"
"iconElement.style.color='#4ecdc4';"
"descElement.textContent='Alta Umidade';"
"}else{"
"iconElement.className='fas fa-sun weather-icon';"
"iconElement.style.color='#ffd93d';"
"descElement.textContent='Condições Ideais';"
"}"
"}"
"function updateTimestamp(){"
"const now=new Date();"
"document.getElementById('timestamp').textContent=now.toLocaleString('pt-BR');"
"}"
"document.addEventListener('DOMContentLoaded',function(){"
"updateWeatherData();"
"setInterval(updateWeatherData,5000);"
"});"
"</script>"
"</body>"
"</html>";

#endif // HTML_DATA_H
